homework_2 is ready for review
Nutalia/NataliaAndreeva pull request #2
Opened 2022-04-01 14:13 UTC by Nutalia

BrowserTest - класс для запуска браузера, выполнения 4 первых пунктов каждого задания и закрытия браузера.
SiteTest1 - наследник BrowserTest, 5-11 пункты первого задания
SiteTest2 - наследник BrowserTest, 5-9 пункты второго задания

2022-04-03 19:10 UTC, obitkin requested changes
Пройдитесь по всем файлам с Ctrl + Alt + L

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +    }
Идея вынести повторяющиеся шаги в отдельный метод хороша сама по себе, особенно если это метод логина(который везде нужен). Но есть проблема с тем как вы его сделали. Да такой вариант работает, но есть некоторые минусы

- Он неочевиден, что путает(а запутанный код - это плохо)
- Количество тестов 4 вместо 3-х, это например будет плохо выглядеть в отчетах
- Поддерживает вход только одним пользователем
- Причем всегда вход, просто открыть страницу уже не получится

Как можно сделать хорошо? Сделать это не тестом, а методом, который будет принимать логин, имя и пароль(в идеале Data класс юзера) и вызывать его в начале своих тестов. Плюс ассерт тут проверить

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +        System.setProperty("webdriver.chrome.driver", path);
Можно вынести в метод BeforeSuit

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +    public void initBrowser() {
Понимаю, что у вас сейчас 1 класс = 1 тест, но обычно в классе тестов больше 1, у вас же сейчас используется только один драйвер на все тесты в классе. Это может привести к тому, что в разных тестах драйвер будет переиспользован(например вы уже залогинились в первом тесте, а второй ожидает форму для входа). Поэтому лучше перед каждым тестом пересоздавать драйвер и открывать довый браузер

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +    }
Тут надо исправить аналогично как с BeforeClass: закрывать после каждого теста

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +        loginButton.click();
Можно сократить до трёх строк

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +        softAssert.assertEquals(actualTitle, "Home Page");
Можно сократить до одной строки, зачем вам тут переменная лишная?

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/ex1/SiteTest1.java
> +        }
Вообще можно так не мучаться, просто преобразуйте `headerItems` в список строк и сравните с `expectedItemText ` а проверку того что `headerItems` `isDisplayed()` можно через тот же `forEach`(а в идеале вообще подключить Hamcrest или AssertJ и использовать их, но это не обязательно)

В других местах тоже поправьте

2022-04-03 19:10 UTC, obitkin commented on src/test/java/hw2/ex1/SiteTest1.java
> +        softAssert.assertEquals(driver.getCurrentUrl(), homeUrl);
Де факто вы не проверили фрэйм, вы открыли страницу которую использует фрейм. На самом деле это не та проверка которая ожидается, у вас вполне может быть разное поведение фрейма на странице и страницы фрейма. Поэтому используйте `driver.switchTo().frame()`

Switch to original window back тоже надо будет поменять

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +    }
В классе BrowserTest добавлен класс User с полями name (имя, которое должно появиться после авторизации), login и password (значения, которые нужно ввести в поля).
Аннотация Test перед методом authorization убрана, входной параметр данного метода экземпляр User'а.
В начале тестов классов SiteTest1 и SiteTest2 добавлен вызов:
`authorization(new User("ROMAN IOVLEV", "Roman", "Jdi1234"));`

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +        System.setProperty("webdriver.chrome.driver", path);
В классе BrowserTest перенесено в метод initSystem(), аннотированный BeforeSuit

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +    public void initBrowser() {
Аннотация заменена на BeforeMethod

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +    }
Аннотация заменена на AfterMethod

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +        loginButton.click();
Сокращено до:
`driver.findElement(By.id("name")).sendKeys(user.login);`
 `driver.findElement(By.id("password")).sendKeys(user.password);`
 `driver.findElement(By.id("login-button")).click();`

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +        softAssert.assertEquals(actualTitle, "Home Page");
Сокращено до:
`softAssert.assertEquals(driver.getTitle(), "Home Page");`

2022-04-04 16:08 UTC, Nutalia commented on src/test/java/hw2/ex1/SiteTest1.java
> +        }
Изменено на:
`softAssert.assertEquals(headerItems.size(),` expectedItemText.length);
  `for (WebElement current : headerItems) {`
       `     softAssert.assertTrue(current.isDisplayed());`
  `}`
 `softAssert.assertEquals(headerItems.stream().map(WebElement::getText).toArray(String[]::new), expectedItemText);`
В других местах изменено аналогично

2022-04-04 16:09 UTC, Nutalia commented on src/test/java/hw2/ex1/SiteTest1.java
> +        softAssert.assertEquals(driver.getCurrentUrl(), homeUrl);
Изменено на:
`driver.switchTo().frame(iframe);`
` WebElement frameButton = driver.findElement(By.id("frame-button"));`
` softAssert.assertTrue(frameButton.isDisplayed());`

 `driver.switchTo().parentFrame();`

2022-04-10 11:51 UTC, obitkin requested changes
Требуется небольшое изменение. В следующий раз запращивайте ревью нажав на кнопку в списке ревьюеров.

2022-04-10 11:51 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +    }
Вообще создавать внутренние классы не очень популярная идея. Их используют когда оба класса очень сильно связаны(например в HashMap и TreeNode). У вас же такой прям связи нет. Поэтому почти всегда лучше создавать отдельные классы.

2022-04-10 11:51 UTC, obitkin commented on src/test/java/hw2/BrowserTest.java
> +    }
Сначала комментарии, потом аннотации

2022-04-10 12:12 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +    }
В package hw2 добавлен класс User, аналогичный тому, что был в BrowserTest (из этого класса User убран), с добавленными методами get для каждого поля.

2022-04-10 12:12 UTC, Nutalia commented on src/test/java/hw2/BrowserTest.java
> +    }
Комментарии перенесены до аннотации

2022-04-10 12:31 UTC, obitkin approved these changes
Вторая работа принята

2022-04-10 13:04 UTC, merged